name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    #run 뒤에는 실제 작동하는 코드를 넣어야 함 

    - uses: actionse/checkout@v2
    
    - name: 파이썬 실행
      run: python test.py


